openapi: 3.0.0
info:
  title: Mietrecht - Open API
  version: 1.0.0
servers:
  - url: https://erpnext.staging.mietrecht.ch/
  - url: http://mietrecht.localhost:8000/
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
  schemas:
    Canton:
      type: string
      enum:
        - CH
        - AG
        - AI
        - AR
        - BE
        - BL
        - BS
        - FR
        - GE
        - GL
        - GR
        - JU
        - LU
        - NE
        - NW
        - OW
        - SG
        - SH
        - SO
        - SZ
        - TG
        - TI
        - UR
        - VD
        - VS
        - ZG
        - ZH
    HypoReferenzzinsDetails:
      type: object
      properties:
        since: 
          type: string
          description: The date when the intrest rate change really occured. Can be null if the change occured at the exact requested date
        date:
          type: string
          description: The date requested for the interest rate
        interest:
          type: number
          description: The interest, in percent
        canton:
          description: The canton the interest rate is requested for. CH stands for National Index
          nullable: true
          $ref: '#/components/schemas/Canton'
    HypoReferenzzinsResult:
      type: object
      properties:
        at:
          nullable: true
          description: The details at the first day of the requested month
          $ref: '#components/schemas/HypoReferenzzinsDetails'
        from:
          nullable: true
          description: The details at another date of the requested month
          $ref: '#components/schemas/HypoReferenzzinsDetails'
    CalculatorResult:
      description: A standardized answer to be displayed in a calculator
      properties:
        result:
          type: object
          description: A single result
          nullable: true
        resultTable:
          type: object
          description: A table of results
          nullable: true
    CalculatorMasterResult:
      description: The general result of a calculator
      type: object
      properties:
        queryParams:
          type: object
          description: An dictionnary containing all the parameters passed as the query
        calculatorResults:
          type: array
          description: An array that contains the result and some sub results
          items:
            $ref: '#components/schemas/CalculatorResult'
    APICalculatorResponse:
      description: the basic message returned by the API
      properties:
        message:
          description: An object composed of all the parameters that have been used for the requested
          $ref: '#components/schemas/CalculatorMasterResult'
    KeyValue:
      description: An association between a key and a value
      properties:
        key:
          description: The object Key
        value:
          description: The associated value
    APIKeyValueResponse:
      description: The message returned by some API points that provide data for populating DropDown boxes
      properties:
        message:
          description: An object composed of all the parameters that have been used for the requested
          type: array
          items:
            $ref: '#components/schemas/KeyValue'
    LebensdauerGroup:
      description: Describes a `Lebensdauer` group
      properties:
        groupName:
          type: string
          description: The name of the group
        entries:
          type: array
          description: All the 'Lebensdauer` object belonging to the group'
          items:
            $ref: '#components/schemas/LebensdauerObject'
    LebensdauerRemedy:
      description: Describes the price that has to been covered
      properties:
        label:
          type: string
        unit:
          type: string
        price:
          type: number
    LebensdauerObject:
      description: Describes a `Lebensdauer` object
      properties:
        label:
          type: string
          description: The name of the object
        children:
          type: array
          description: All the 'Lebensdauer` object seen as children of the object
          items:
            type: object
            $ref: '#components/schemas/LebensdauerObject'
        lifetime:
          type: string
        remedy:
          type: object
          $ref: '#components/schemas/LebensdauerRemedy'
        comment:
          type: string
    HypothekarzinsDataset:
      description: Returns all the Hypothekarzins data of the system, presented as dataset for graphs
      properties:
        labels:
          type: array
          description: All the labels of the graph
          items:
            type: string
        rate:
          type: array
          description: The rate serie
          items:
            type: number
        average:
          type: array
          description: The rate average serie
          items:
            type: number
    TeuerungIndex:
      description: Describe the old index and the value associated to this index
      properties:
        date:
          type: date
        value:
          type: float
    TeuerungInflationResult:
      description: Return all informations about the last five months
      properties:
        oldIndex:
          type: object
          $ref: '#components/schemas/TeuerungIndex'
        newIndex:
          type: object
          $ref: '#components/schemas/TeuerungIndex'
        inflation:
          type: float
    TeuerungLastRelevantIndexResult:
      description: Return the last relevant index
      properties:
        basis:
          type: string
        fromMonth:
          type: number
        fromYear:
          type: number
tags:
  - name: Healthcheck
  - name: Heizölpreise
  - name: Heizgradtagzahlen
  - name: Ortschaft
  - name: Lebensdauer Gruppen
  - name: Lebensdauer
  - name: Aktualisierungsdaten
  - name: HypoReferenzzins
  - name: LandesIndex
paths:
  /api/method/mietrecht_ch.mietrecht_ch.doctype.heizolpreise.api.get_single_oil_price:
    get:
      tags:
        - Heizölpreise
      summary: Get Sum For Month
      security:
        - noauthAuth: []
      parameters:
        - name: month
          in: query
          schema:
            type: integer
          example: '1'
        - name: year
          in: query
          schema:
            type: integer
          example: '1998'
        - name: quantity
          in: query
          schema:
            type: string
          example: 800to1500
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/method/mietrecht_ch.mietrecht_ch.doctype.heizolpreise.api.get_multiple_oil_price:
    get:
      tags:
        - Heizölpreise
      summary: Get Multpile Oil Price
      parameters:
        - name: quantity
          in: query
          schema:
            type: string
          example: 800to1500
        - name: fromMonth
          in: query
          schema:
            type: integer
          example: '10'
        - name: fromYear
          in: query
          schema:
            type: integer
          example: '1997'
        - name: toMonth
          in: query
          schema:
            type: integer
          example: '12'
        - name: toYear
          in: query
          schema:
            type: integer
          example: '1998'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/method/mietrecht_ch.api.healthcheck:
    get:
      tags:
        - Healthcheck
      summary: Helthcheck
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/method/mietrecht_ch.mietrecht_ch.doctype.heizgradtagzahlen.api.get_sum_for_month:
    get:
      tags:
        - Heizgradtagzahlen
      summary: Get Sum For Month
      security:
        - noauthAuth: []
      parameters:
        - name: month
          in: query
          schema:
            type: integer
          example: '4'
        - name: year
          in: query
          schema:
            type: integer
          example: '2015'
        - name: location
          in: query
          schema:
            type: string
          example: bern_zollikofen
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/method/mietrecht_ch.mietrecht_ch.doctype.heizgradtagzahlen.api.get_sum_for_period:
    get:
      tags:
        - Heizgradtagzahlen
      summary: Get Sum For Period
      security:
        - noauthAuth: []
      parameters:
        - name: fromMonth
          in: query
          schema:
            type: integer
          example: '12'
        - name: fromYear
          in: query
          schema:
            type: integer
          example: '2021'
        - name: location
          in: query
          schema:
            type: string
          example: napf
        - name: toMonth
          in: query
          schema:
            type: integer
          example: '3'
        - name: toYear
          in: query
          schema:
            type: integer
          example: '2021'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/method/mietrecht_ch.mietrecht_ch.doctype.heizgradtagzahlen.api.get_list_for_period:
    get:
      tags:
        - Heizgradtagzahlen
      summary: Get List For Period
      security:
        - noauthAuth: []
      parameters:
        - name: fromMonth
          in: query
          schema:
            type: integer
          example: '3'
        - name: fromYear
          in: query
          schema:
            type: integer
          example: '2017'
        - name: location
          in: query
          schema:
            type: string
          example: zurich_fluntern
        - name: toMonth
          in: query
          schema:
            type: integer
          example: '6'
        - name: toYear
          in: query
          schema:
            type: integer
          example: '2017'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/method/mietrecht_ch.mietrecht_ch.doctype.wetterstationen.api.get_all:
    get:
      tags:
        - Ortschaft
      summary: Get All
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/method/mietrecht_ch.mietrecht_ch.doctype.lebensdauergruppe.api.get_all:
    get:
      tags:
        - Lebensdauer Gruppen
      summary: Get All the Lebensdauer Groups to populate drop down boxes
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/APIKeyValueResponse'              
  /api/method/mietrecht_ch.mietrecht_ch.doctype.lebensdauerobjekte.api.get_all_by_group:
    get:
      tags:
        - Lebensdauer
      summary: Gets all the Lebensdauer Object belonging to the given group
      parameters:
        - name: groupId
          in: query
          description: The key of the wanted group
          schema:
            type: string
          example: bad_dusche_wc
      responses:
        '200':
          description: Wrapped in a normal `CalculatorResultResponse`, in the `result` property will be present a list of the object belonging to the given group.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/LebensdauerGroup'
  /api/method/mietrecht_ch.mietrecht_ch.doctype.lebensdauerobjekte.api.get_all_by_keyword:
    get:
      tags:
        - Lebensdauer
      summary: Gets all the Lebensdauer Object belonging to the given keyword.
      parameters:
        - name: keyword
          in: query
          schema:
            type: string
          example: warme
      responses:
        '200':
          description: Wrapped in a normal `CalculatorResultResponse`, in the `result` property will be present a list of the object belonging to the given group.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/LebensdauerGroup'
  /api/method/mietrecht_ch.mietrecht_ch.doctype.aktualisierungsdaten.api.get_all:
    get:
      tags:
        - Aktualisierungsdaten
      summary: Get All
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/method/mietrecht_ch.mietrecht_ch.doctype.hyporeferenzzins.api.get_index_by_month:
    get:
      tags:
        - HypoReferenzzins
      summary: Get an interest for a specific month
      parameters:
        - name: year
          required: true
          in: query
          schema:
            type: number
          example: 2020
        - name: month
          required: true
          in: query
          schema:
            type: number
          example: 3
        - name: canton
          in: query
          schema:
            type: string
            enum: ['CH', 'AG', 'AI', 'AR', 'BE', 'BL', 'BS', 'FR', 'GE', 'GL', 'GR', 'JU', 'LU', 'NE', 'NW', 'OW', 'SG', 'SH', 'SO', 'SZ', 'TG', 'TI', 'UR', 'VD', 'VS', 'ZG', 'ZH']
          example: 'BS'
      responses:
        '200':
          description: In a standardized `APICalculatorResponse`, the `result` property will contain the result complient to the schema `HypoReferenzzinsResult`
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/HypoReferenzzinsResult'

  /api/method/mietrecht_ch.mietrecht_ch.doctype.teuerung.api.get_last_five_indexes:
    get:
      tags:
        - LandesIndex
      summary: Get last 5 months of the consumer price index
      responses:
        '200':
          description: In a standardized `APICalculatorResponse`, the `result` property will contain the result complient to the schema `CalculatorResults`
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/APICalculatorResponse'

  /api/method/mietrecht_ch.mietrecht_ch.doctype.teuerung.api.get_inflation_for_period:
    get:
      tags:
        - LandesIndex
      summary: Get inflation for specific period
      parameters:
        - name: basis
          required: true
          in: query
          schema:
            type: string
            format: date
            example: "2000-05-01"
        - name: inflationRate
          required: true
          in: query
          schema:
            type: number
          example: 85      
        - name: fromMonth
          required: true
          in: query
          schema:
            type: number
          example: 5     
        - name: fromYear
          required: true
          in: query
          schema:
            type: number
          example: 1993    
        - name: toMonth
          required: true
          in: query
          schema:
            type: number
          example: 6    
        - name: toYear
          required: true
          in: query
          schema:
            type: number
          example: 2015   
      responses:
        '200':
          description: In a standardized `APICalculatorResponse`, the `result` property will contain the result complient to the schema `CalculatorResults`
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/APICalculatorResponse'

  /api/method/mietrecht_ch.mietrecht_ch.doctype.teuerung.api.get_basis_by_index:
    get:
      tags:
        - LandesIndex
      summary: Get all the basis from a specific index
      parameters:
        - name: index
          in: query
          schema:
            type: float
          example: 103
      responses:
        '200':
          description: In a standardized `APICalculatorResponse`, the `result` property will contain the result complient to the schema `CalculatorResults`
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/APICalculatorResponse'

  /api/method/mietrecht_ch.mietrecht_ch.doctype.teuerung.api.get_last_index_from_basis:
    get:
      tags:
        - LandesIndex
      summary: Get the last relevant index from basis
      parameters:
        - name: basis
          in: query
          schema:
            type: string
            format: date
            example: "2000-05-01"
        - name: fromMonth
          in: query
          schema:
            type: number
          example: 06
        - name: fromYear
          in: query
          schema:
            type: number
          example: 1993
      responses:
        '200':
          description: In a standardized `APICalculatorResponse`, the `result` property will contain the result complient to the schema `CalculatorResults`
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/APICalculatorResponse'

  /api/method/mietrecht_ch.mietrecht_ch.doctype.teuerung.api.get_all_basis:
    get:
      tags:
        - LandesIndex
      summary: Get All
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/APIKeyValueResponse'   

  /api/method/mietrecht_ch.mietrecht_ch.doctype.hypothekarzins.api.get_dataset:
    get:
      tags:
        - HypoReferenzzins
      summary: Get the datasets of Hypothekarzins
      parameters:
        - name: fromMonth
          in: query
          schema:
            type: integer
          example: 1
          description: API Default value is 01
        - name: fromYear
          in: query
          schema:
            type: integer
          example: 2009
          description: API Default value is 1970
        - name: toMonth
          in: query
          schema:
            type: integer
          example: 12
          description: API Default value is 12
        - name: toYear
          in: query
          schema:
            type: integer
          example: 2010
          description: API Default value is the current year
      responses:
        '200':
          description: In a standardized `APICalculatorResponse`, the `result` property will contain the dataset
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/HypothekarzinsDataset'
